server:
  port: ${PORT:9090}

spring:
  application:
    name: srv-config-server
  cloud:
    config:
      server:
        git:
          uri: ${GIT_CONFIG_URI}
          username: ${GIT_USER_NAME}
          password: ${GIT_USER_PASSWORD}
          clone-on-start: true
          default-label: master
          search-paths: ${CONFIG_FILES:configFiles}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:9091/eureka/}
    register-with-eureka: true
    fetch-registry: true
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
