FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY build/libs/msa-customer-management-1.0.1.jar /app/msa-customer-management-1.0.1.jar
EXPOSE 8080
CMD ["java", "-jar", "/app/msa-customer-management-1.0.1.jar"]
