FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY target/msa-account-transaction-1.0-SNAPSHOT.jar /app/msa-account-transaction-1.0-SNAPSHOT.jar
EXPOSE 8080
CMD ["java", "-jar", "/app/msa-account-transaction-1.0-SNAPSHOT.jar"]